bin/spark-evaluate.js

Before my change, the evaluation step was failing with the following
error:
TypeError: Cannot read properties of undefined (reading 'error')
at file:///app/lib/preprocess.js:17:16
at Array.filter (<anonymous>)
at preprocess (file:///app/lib/preprocess.js:12:6)
In this change, I am setting up a console logger in the main entry point.
Connect to:
- https://github.com/filecoin-station/spark/issues/13

fix: setup console logger

---

lib/telemetry.js
test/evaluate.js
test/preprocess.js

Before my change, there was a delay of approx. two seconds after all tests complete but before the Mocha process exits. This delay was caused by the recently added InfluxDB client (commit 09aaffcfe).
This commit modifies the test suite to explicitly close the InfluxDB client after all tests are finished.

test: remove delay after all tests are done

---

lib/preprocess.js
test/preprocess.js

Before this change, we would reject measurements with no participant
address with an ugly error:
```
Invalid measurement: Cannot read properties of undefined (reading 'startsWith') {
```
In this commit, I changed the address parser to map measurements with
missing participant address to the same hard-coded `0xf100` participant
as we map `f1`/`t1` participants.
This is a follow-up for #10

fix: handle missing `participant_address`

---

bin/spark-evaluate.js
index.js
lib/evaluate.js
lib/preprocess.js
lib/telemetry.js
test/evaluate.js
test/preprocess.js

Modify the processing pipeline to accept the `record` function via dependency injection.
Rework the test suite to supply a dummy no-op `record` function so we don't corrupt telemetry data from production with telemetry submitted by tests.
Links to:
- https://github.com/filecoin-station/spark/issues/13
- https://github.com/filecoin-station/spark/issues/18

fix: don't record telemetry from tests

---

lib/evaluate.js
lib/preprocess.js

Example of preprocessing logs:
```
PREPROCESS ROUND 0: Added measurements from CID bafybeif2
{ total: 1, valid: 1 }
```
Example of evaluation logs:
```
EVALUTE ROUND 0: Evaluated 10 measurements, found 10 honest entries.
{ OK: 10, INVALID_TASK: 0 }
EVALUTE ROUND 0: Invoking IE.setScores(); number of participants: 1, total score: 100%
EVALUTE ROUND 0: IE.setScores() TX hash: 0x234
```

feat: improve logging

---

lib/evaluate.js
lib/spark-api.js
test/evaluate.js
test/spark-api.js

Rework `fetchRoundDetails` to invoke the API endpoint that returns SPARK round details for the provided IE contract address & round index.
Links:
- https://github.com/filecoin-station/spark/issues/13
- https://github.com/filecoin-station/spark-api/pull/103

fix: fetch SPARK round details by IE round

---

lib/spark-api.js
lib/typings.d.ts

Fix the following error by changing the field type from int to string:
```
Event: RoundStart { roundIndex: 327 }
Error: invalid integer value for field 'contract_address': '0x3113b83ccec38a18df936f31297de490485d7b2e'!
at ve.intField (file:///app/node_modules/@influxdata/influxdb-client/dist/index.mjs:4:2656)
at file:///app/lib/spark-api.js:23:13
at recordTelemetry (file:///app/lib/telemetry.js:20:3)
at fetchRoundDetails (file:///app/lib/spark-api.js:22:5)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async evaluate (file:///app/lib/evaluate.js:19:29)
```
Also add types for the function `recordTelemetry()` to make it easier to discover Point methods available for different data types.
Links:
- https://github.com/filecoin-station/spark/issues/13

fix: telemetry field type for contract address

---

bin/spark-evaluate.js
index.js
lib/preprocess.js
test/preprocess.js

Rework the preprocessor to expect a function with a simpler signature for retrieving measurements stored in the given CID.
This simplifies existing unit tests and enables future work like anonymous "dry-run" (see #31)

refactor: simplify injection of fetchMeasurements

---

README.md
bin/dry-run.js

Example:
```
❯ node bin/dry-run.js 0x3113b83ccec38a18df936f31297de490485d7b2e 273 bafybeie5rekb2jox77ow64wjjd2bjdsp6d3yeivhzzd234hnbpscfjarv4
Evaluating round 273 of contract 0x3113b83ccec38a18df936f31297de490485d7b2e
==PREPROCESS==
PREPROCESS ROUND 273: Added measurements from CID bafybeie5rekb2jox77ow64wjjd2bjdsp6d3yeivhzzd234hnbpscfjarv4
{ total: 16, valid: 16 }
Fetched 16 measurements
==EVALUATE==
EVALUTE ROUND 273: Evaluated 16 measurements, found 15 honest entries.
{ OK: 15, INVALID_TASK: 1 }
EVALUTE ROUND 273: Invoking IE.setScores(); number of participants: 2, total score: 999999999999999n
==EVALUATION RESULTS==
participants: [
'0xf100Ac342b7DE48e5c89f7029624eE6c3Cde68aC',
'0x000000000000000000000000000000000000dEaD'
]
scores: [ 933333333333333n, 66666666666666n ]
==END OF …
```

feat: add a bin script to run evaluation locally

---

.github/workflows/ci.yml

Follow-up for https://github.com/filecoin-station/spark-evaluate/pull/45

ci: don't deploy if we cannot build Docker image

---

lib/evaluate.js
test/evaluate.js

Ensure all scores add up to `MAX_SCORE` by adding a new entry assigning the remainder to the special address `0x000[...]000000000000000dEaD`.
The smart contract recognises this address and does not pay any rewards to it.
Resolve #49

feat: round scores to MAX_SCORE

---

bin/dry-run.js

I am investigating why we get `undefined` fraud assessments in our evaluations. To speed up the dry-run evaluations, I want to cache measurements to speed up sub-sequent dry-run evaluations of the same round.

feat: cache fetched measurements in dry-run tool

---

lib/evaluate.js
lib/telemetry.js
test/evaluate.js

Now that our CID dataset has ~300k items, there is little value in observing the count of samples. Instead, I would like to see how many unique retrieval tasks we are able to test each round and over time.
In this change, I am adding a new field to the existing telemetry point "evaluate" with the count of unique tasks found in the honest measurements.
While we could get this data by querying the `measurements` table, such query is extremely expensive and cannot filter out measurements not considered as honest.
Links:
- https://github.com/filecoin-station/roadmap/issues/43

feat: report unique tasks in honest measurements

---

lib/evaluate.js
lib/preprocess.js
lib/retrieval-stats.js
lib/typings.d.ts
package-lock.json
package.json
test/evaluate.js
test/helpers/assertions.js
test/helpers/test-data.js
test/preprocess.js
test/retrieval-stats.test.js

To rework our Grafana dashboards to source metrics from InfluxDB instead of Postgres, I am implementing a new telemetry point that will be submitted for each evaluated round.
Point names:
- `retrieval_stats_honest` - only measurements assessed as honest
- `retrieval_stats_all` - all measurements, including those potentially fraudulent
Fields:
- `round_index`
- `unique_tasks` - how many unique CIDs we tested
- `success_rate` - how many retrievals ended up with success
- `result_rate_{result}` - breakdown of different retrieval results, e.g. `result_rate_OK`
- `inet_groups` - number of unique IPv4 /24 subnets
- `measurements` - number of measurements
- `download_bandwidth`
- `participants`
- Histograms - the following values are reported for all fields: `min`, `mean`, `max`, `p10`, `p50`, …

feat: report per-round retrieval stats to InfluxDB

---

lib/evaluate.js
test/evaluate.js

See https://github.com/filecoin-station/spark-evaluate/commit/ddfe10abd91eb440f1e5f0608b6778a737f15b81

fix: re-enable `group_winning_{min,max,mean}`

---

lib/retrieval-stats.js
test/retrieval-stats.test.js

When the retrieval fails, `end_at` and `first_byte_at` are set to unix epoch (1970-01-01T00:00:00.000Z). We need to ignore such measurements when calculating ttfb & duration stats.
Links:
- https://github.com/filecoin-station/spark-api/issues/144
- https://github.com/filecoin-station/spark-evaluate/pull/67

fix: retrieval stats - ttfb & duration

---

lib/preprocess.js
lib/typings.d.ts
test/preprocess.js

Fix `getRetrievalResult()` to correctly handle measurements where `status_code` is not 2xx.
Links:
- https://github.com/filecoin-station/spark-api/issues/144
- https://github.com/filecoin-station/spark-evaluate/pull/67

fix: measurements with status_code set to null

---

README.md
bin/dry-run.js
bin/spark-evaluate.js
lib/preprocess.js
package-lock.json
package.json

Files are now published to the root entry of the CID (vs at `/measurements.json`), therefore this PR and the `spark-api` PR need to be merged together.
Links:
- https://github.com/filecoin-station/spark-api/issues/141

Update web3.storage API

---

bin/dry-run.js
lib/evaluate.js
lib/preprocess.js
lib/round.js
test/evaluate.js
test/preprocess.js

For each round, keep a lookup table with all known string values.  When creating a new Measurement instance, replace incoming string values with the cached string instances.
This reduces memory usage by another ~70%.
**Before:**
```
{
rss: 893943808,
heapTotal: 570556416,
heapUsed: 540473960,
external: 5228292,
arrayBuffers: 76335
}
```
**After:**
```
{
rss: 561840128,
heapTotal: 458522624,
heapUsed: 407380752,
external: 5660805,
arrayBuffers: 559664
}
```
**After pointerizing provider_address:**
```
{
rss: 3752099840,
heapTotal: 167313408,
heapUsed: 161246552,
external: 3754973060,
arrayBuffers: 35375
}
```

perf: cache string values

---

lib/preprocess.js
lib/retrieval-stats.js
test/retrieval-stats.test.js

- fix: keep `status_code` in parsed measurements
- fix: ignore `byte_length` for non-200 status code

fix: retrieval stats (ttfb, car_size)

---

lib/retrieval-stats.js
test/retrieval-stats.test.js

JavaScript's `sort()` method sort lexicographicaly, i.e. `10` < `2`.
I am fixing this problem by providing a custom comparator.

fix: sorting of values for histogram calculations

---

lib/evaluate.js
lib/retrieval-stats.js
test/retrieval-stats.test.js

Help us understand how many data points we have for each task (what is the effective committee size). Are the committees always large enough to give us enough confidence in finding an honest majority?
Also, record how many measurements (retrieval checks) we provide for each task to understand how much load we put on SPs.
InfluxDB point name: `committees`
Field prefixes:
- `subnets_`
- `participants_`
- `instances_`
- `measurements_` (all measurements, independent of fraud assessment)
Links:
- https://github.com/filecoin-station/spark-api/pull/171
- https://github.com/filecoin-station/spark/issues/45
- https://github.com/filecoin-station/roadmap/issues/52

feat: record subnets/participants/instances per task

---

lib/evaluate.js
test/evaluate.js
test/spark-api.js

- test: handle maxTasksPerNode in round details
- feat: report ~~instances~~ nodes participating in a round
Count the number of unique `(inet_group, participant_address)` nodes participating in the evaluated round and record it as another telemetry field.
Point name: `evaluate`
Field name: `total_nodes`
**IMPORTANT: the number of nodes calculated this way WILL BE DIFFERENT from the number of Station instances obtained from "ping" points.**
Related:
- https://github.com/filecoin-station/spark-evaluate/pull/97

feat: report nodes participating in a round

---

lib/evaluate.js
test/evaluate.js

In order not to run into smart contract argument length limitations

limit `setScores` arguments length

---

bin/fetch-measurements.js
package-lock.json
package.json

This is a follow-up for https://github.com/filecoin-station/spark-api/pull/184. My intention is to implement the integration bits while I remember the details. Improving the new script to store measurements in a more useful format (e.g. feed it to Postgres or SQLite) is out of the scope.
Example usage:
```
❯ DATABASE_URL="postgres://redacted:redacted@localhost:5454/spark" node bin/fetch-measurements.js 2024-01-04T00:00:00Z 2024-01-04T00:15:00Z> measurements.ndjson
Fetching measurements committed between "2024-01-04T00:00:00.000Z" and "2024-01-04T00:15:00.000Z"
Found 8 commitments
fetching bafybeihpv77mcbbnkss7umjcnjcvizki3nky7s5kh2ys2upvx6skjxf5lm
fetching bafybeicnmtnrnrbcejabdxm264ttt2obmke2acsriww7lbopp66zewmoia
fetching bafybeieeqbdovjpwsd5f4fudhhkwa4p6c6fzgsmyxksve5dsx6ic3ej4d4 …
```

feat: add a script to fetch committed measurements

---

lib/retrieval-stats.js
package-lock.json
package.json
test/retrieval-stats.test.js

Refactor our code calculating percentiles to use a 3rd party dependency instead of our own implementation.
I discovered this while thinking how to address the discussion in my blog post:
https://github.com/bajtos/bajtos.github.io/pull/23#discussion_r1426613735
It makes me wonder why I didn't find this npm package before!
Sometimes, it's better to have more control over our code and not use 3rd-party dependencies for simple helper functions, so maybe this PR isn't an improvement.
Thoughts?

refactor: use `just-percentile` instead of own impl

---

lib/evaluate.js

When the smart contract call fails, report the error and keep going.  This error is not recoverable, but we need to report metrics and clean up the round data.

fix: handle failure of ieContract.setScores()

---

.github/workflows/ci.yml
README.md
bin/migrate.js
bin/spark-evaluate.js
index.js
lib/config.js
lib/evaluate.js
lib/migrate.js
lib/public-stats.js
lib/typings.d.ts
migrations/001.do.retrieval-stats.sql
package-lock.json
package.json
test/evaluate.js
test/helpers/test-data.js

A prototype implementing code for producing stats to power our Spark Public Dashboard. Design doc: 
https://pl-strflt.notion.site/DB-for-SPARK-public-data-a79cbb7a0ff5447980b714afdb2645d6
1. Add a runtime dependency on a PG database, using a new database
name `spark_stats` (originally: ~~`spark_public`~~). Setup database schema migrations executed
at service startup.
2. Define the first table `retrievals` to keep stats about all vs
succesfull retrievals performed each day.
3. Update the evaluate step to update these stats for each round
completed.
**TODO**
Links:
- https://github.com/filecoin-station/roadmap/issues/57

feat: write public stats to our PG DB

---

lib/config.js
lib/evaluate.js
lib/public-stats.js
test/evaluate.js

Based on our live discussion, we want to calculate the Retrieval Success Rate from measurements that passed fraud detection.
Links:
- https://github.com/filecoin-station/roadmap/issues/57

fix: calculate RSR using honest measurements only

---

bin/dry-run.js

This is a follow-up for #122 to fix the dry-run script.
Links:
- https://github.com/filecoin-station/roadmap/issues/57

fix: setup a no-op PG client in dry-run

---

lib/public-stats.js
migrations/003.do.daily-participants.sql
test/public-stats.test.js

Create a new `spark_stats` table to keep track of daily participants:
```sql
SELECT day::TEXT, COUNT(DISTINCT participant_id) as count
FROM daily_participants GROUP BY day;
```
This table allows us to correctly calculate monthly participants too:
```sql
SELECT
date_trunc('month', day)::DATE::TEXT as month,
COUNT(DISTINCT participant_id) as count
FROM daily_participants
GROUP BY month;
```
TODO:
Links:
- https://github.com/filecoin-station/spark-evaluate/issues/79

feat: report daily participants to public stats

---

lib/evaluate.js
lib/preprocess.js
lib/retrieval-stats.js
lib/typings.d.ts
test/evaluate.js
test/helpers/test-data.js
test/retrieval-stats.test.js

When checking whether a measurement is for a valid round task, compare both `cid` and `minerId` fields
When picking a checker node in an IPv4 subnet to receive the reward, include `minerId` in the grouping key: When two nodes in the same subnet retrieve the same CID but from different miners, they should be both rewarded.
In practice, this second change will manifest very infrequently, because it's unprobable to have a single round with two tasks for the same CID.  As a result, I did not need to make any changes to the integration test running against real measurements.
Links:
- https://github.com/filecoin-station/spark-evaluate/pull/176
- https://github.com/filecoin-station/roadmap/issues/65
**Out of scope:**
Covered by future tasks in …

feat: include minerId in task definition

---

lib/public-stats.js
migrations/005.do.miner-retrieval-stats.sql
test/evaluate.js
test/public-stats.test.js

I verified that read queries executed by [spark-stats](https://github.com/filecoin-station/spark-stats/) keep working with the new DB schema.
Links:
- https://github.com/filecoin-station/roadmap/issues/65

feat: record RSR per miner id

---

lib/telemetry.js

Telemetry points have a lot of fields. Printing them via console.log puts too much pressure on our log ingestion system.
This commit changes `console.log()` to `debug()` to keep these logs available during development.

fix: print telemetry via debug log

---

fly.toml

To ensure only one instance is running at a time

set deploy strategy to rolling

---

README.md
bin/dry-run.js
lib/config.js
package-lock.json
package.json

Improve `bin/dry-run.js` to fetch the index of the last round from on-chain state.
Add dotenv integration to allow developers to keep the Glif API token in the `.env` file.

feat: dry run for the last round

---

.github/workflows/ci.yml
bin/dry-run.js
lib/evaluate.js

Our test suite uses relatively small datasets to test the evaluation pipeline. In this PR, I am adding another build/test step to dry-run the evaluation of a real round, to catch possible errors that are triggered only by large datasets.
Additional changes to make this new CI step useful:
- fix: calculation of the last round index
- feat: write stats to a real DB in dry-run
- fix: remove noisy event log in dry-run 
- report duration of the `evaluate()` call
- feat: crash dry-run on errors ignored in production
This PR is a follow-up for
- https://github.com/filecoin-station/spark-evaluate/pull/194
/cc @PatrickNercessian

ci: dry-run evaluation of the last Spark round

---

lib/platform-stats.js
lib/preprocess.js
test/platform-stats.test.js

Fixes dry run error
```
error: null value in column "station_id" of relation "daily_stations" violates not-null constraint
```

platform-stats: fix ignore empty station id

---

lib/platform-stats.js
lib/public-stats.js
test/platform-stats.test.js
test/public-stats.test.js

Let's make it easier to share the code that's building participant-related stats between all Meridian projects (Spark, Voyager). One baby step at a time.
/cc @PatrickNercessian

refactor: move participant stats to platform stats

---

.github/workflows/ci.yml
bin/dry-run.js
bin/get-unique-measurement-values.js
bin/spark-evaluate.js
index.js
lib/evaluate.js
lib/migrate.js
lib/platform-stats.js
lib/preprocess.js
lib/public-stats.js
lib/retrieval-stats.js
lib/round.js
lib/spark-api.js
lib/typings.d.ts
package-lock.json
package.json
tsconfig.json

1. Configure TypeScript checking (locally and as part of the CI)
2. Fix TypeScript errors
See https://github.com/filecoin-station/roadmap/issues/80
The content of `tsconfig.json` is from station-core:
https://github.com/filecoin-station/core/blob/01e9a9f6169c6df5dc152bf7d89b04bade3e5d70/tsconfig.json)
Out of scope/follow-up issues:
- https://github.com/filecoin-station/on-contract-event/issues/2

chore: setup TypeScript type checking

---

index.js

As suggested in https://filecoinproject.slack.com/archives/C031K3BG527/p1714658724173009?thread_ts=1714636341.173339&cid=C031K3BG527. Data stored in W3S isn't always immediately available, and especially sometimes trying to fetch it too soon will result in bad responses in the caches.

preprocess: add delay to improve changes of data being available

---

bin/dry-run.js
lib/preprocess.js

Noticed in https://github.com/filecoin-station/spark-evaluate/actions/runs/8995936280/job/24711656364?pr=205 that it can take a while. While most of the time there is waiting for w3s data to become available, even without it will take minutes

perf: speed up `bin/dry-run.js`

---

lib/evaluate.js
lib/typings.d.ts
test/evaluate.js
test/helpers/assertions.js
test/integration.test.js

These stats are difficult to understand. Thefeore, we haven't been using them for a while now.
My work on fixing the per-inet-group reward selection in #225 would require us to significantly rework the way how to calculate these stats. I decided it's not worth the effort.
As of #223, we are recording slightly different stats about per-inet-group rewards, so we will still have some visibility into this area.

feat: remove "inet group success rate" stats

---

lib/evaluate.js
test/evaluate.js
test/integration.test.js

Rework the rewards awarded to each inet-group so that:
- We reward at most `maxTasksPerNode` measurements in each inet group, regardless of which task they belong to
- We reward only the first measurement for each task 
Links:
- https://github.com/filecoin-station/spark-evaluate/pull/223
- https://github.com/filecoin-station/spark-evaluate/pull/226

fix: rewards per inet group

---

index.js

A temporary hacky fix for #64. See also #209.

fix: delay evaluation to finish preprocessing

---

Dockerfile

Get rid of the following warning printed by Sentry:
```
[Sentry] You are using Node.js in ESM mode ("import syntax"). The Sentry
Node.js SDK is not compatible with ESM in Node.js versions before
18.19.0 or before 20.6.0. Please either build your application with
CommonJS ("require() syntax"), or use version 7.x of the Sentry Node.js
SDK.
```

feat: upgrade Node.js to v20.13.1 (latest LTS)

---

index.js

Fix the regression introduced by #224 where the first measurements batch added to a new round triggers the following error:
```
Round index mismatch: 7386 !== 7387
```
Sentry issue:
https://space-meridian.sentry.io/issues/5385606165/?project=4505906069766144

fix: advance round before waiting for preprocess

---

index.js

Rework the handler to report the error to stderr & Sentry and ignore the event instead of crashing the process.
Related:
- https://github.com/filecoin-station/spark-evaluate/issues/64
- #224
- #230
Sentry issue:
- https://space-meridian.sentry.io/issues/5385606165/
- plus many more, because each error had a unique message due to the included round index

fix: handle round mismatch on MeasurementsAdded

---

bin/fetch-recent-miner-measurements.js
lib/preprocess.js
package-lock.json
package.json

Add a script enabling storage providers to inspect recent Spark measurements for content they are storing.
**Example usage:**
```
node bin/fetch-recent-miner-measurements.js f010479
```
**Example output in measurements-f010479.txt**
```
Timestamp                CID                                                                    Protocol   RetrievalResult
2024-05-24T02:43:14.371Z bafybeigpefr2xxsiigy5witxbmgrg3ok7tnrauz44z3utch5uxakljxlki            http       BAD_GATEWAY
2024-05-24T02:43:19.564Z bafybeigpefr2xxsiigy5witxbmgrg3ok7tnrauz44z3utch5uxakljxlki            http       BAD_GATEWAY
2024-05-24T02:43:28.086Z bafybeigpefr2xxsiigy5witxbmgrg3ok7tnrauz44z3utch5uxakljxlki            http       BAD_GATEWAY
2024-05-24T02:43:30.087Z …
```

feat: bin/fetch-recent-miner-measurements.js

---

README.md
lib/config.js

Update the docs and the default config to use the new database name.
- https://github.com/filecoin-station/roadmap/issues/109

chore: rename DB `spark_stats` to `spark_evaluate`

---

README.md
bin/dry-run.js
lib/config.js

Modify the dry-run script to read the environment variable DUMP and save evaluated measurements to a CSV file when the env var is set.
The CSV file can be easily converted to a spreadsheet, which makes it easy to perform further data analysis.
**Example usage**
Dump all measurements:
```
❯ DUMP=1 node bin/dry-run.js 7970
(...lots of logs...)
Evaluated measurements saved to measurements-7970-all.csv
```
Dump measurements for miner with id `f0123`:
```
❯ DUMP=f0123 node bin/dry-run.js 7970
(...lots of logs...)
Storing measurements for miner id f0123
Evaluated measurements saved to measurements-7970-f0123.csv
```
Dump measurements submitted by participant with address `0xdead`:
```
❯ DUMP=0xdead node bin/dry-run.js 7970
(...lots of logs...)
Storing measurements from participant address …
```

feat: dump evaluated measurements after dry run

---

bin/fetch-recent-miner-measurements.js
lib/evaluate.js

Improve the script `fetch-recent-miner-measurements.js` to group measurements into rounds and apply fraud detection to reject measurements not contributing to the retrieval success rate score shown by Spark dashboards.
When the env var `KEEP_REJECTED` is set, include both accepted and rejected measurements in the output, and write the `fraudAssesment` field too.
When `KEEP_REJECTED` is not set, only accepted measurements are written and the `fraudAssesment` field is hidden from the user.

feat: fraud detection when fetching miner data

---

bin/fetch-recent-miner-measurements.js

After fetching recent miner measurements, print a summary of what retrieval results seen and their frequency.
_I hacked this together very quickly; the code & names may not be up to our standards. Let me know what parts to improve!_

feat: report retrieval result break-down

---

bin/fetch-recent-miner-measurements.js

The script `bin/fetch-recent-miner-measurements.js` takes very long to complete. Usually, I abort it after collecting enough measurements.
This change adds a log message with the number of miner measurements found in each round. This makes it easier to know when we have collected enough measurements and can abort the script.

feat: show progress in discovering miner measurements

---

migrations/011.do.daily-stations-idx-day.sql

Speed up spark-stats queries, they always filter by a date range.
Before - 7.2 seconds:
```
->  Parallel Seq Scan on daily_stations  (cost=0.00..899791.13 rows=2746355 width=144) (actual time=273.312..7516.967 rows=2091389 loops=3)
Filter: (day = date((now() - '1 day'::interval)))
Rows Removed by Filter: 8091296
```
After - 0.8 seconds:
```
->  Parallel Index Scan using daily_stations_day on daily_stations  (cost=0.45..283087.78 rows=2746355 width=144) (actual time=143.526..988.537 rows=2091389 loops=3)
Index Cond: (day = date((now() - '1 day'::interval)))
```
I tested various combinations of indexed and included columns. The simplest option - index on the date value only - is performing best.
Links:
- https://github.com/filecoin-station/spark-stats/pull/164

feat: index daily_stations by day

---

lib/evaluate.js

I noticed the error log has incorrect format:
```
CANNOT SUBMIT SCORES FOR ROUND %S (CALL 12059n/4): 11 Error: (...)
```
The problem is that `%S` is not recognized as a formatting directive.
This commit fixes the log format to use `%s` instead.

fix: error log format on score tx errors

---

lib/preprocess.js
lib/typings.d.ts
test/helpers/test-data.js

The following fields are present in raw measurements stored in
web3.storage, let's add them to our Measurements object:
-  timeout
-  car_checksum
-  car_too_large
Links:
- https://github.com/space-meridian/roadmap/issues/59

feat: add more fields to Measurements object

---

lib/public-stats.js
test/public-stats.test.js

Fix a regression introduced by 49252980 (#304).
With the recently introduced “committees & majorities”, measurements that don’t agree with the majority are rejected. As a result, the code calculating RSR will receive only majority measurements, it will see that either a) all accepted measurements say the deal is retrievable or b) all accepted measurements say the deal is not retrievable. As a result, the RSR is heavily influenced by how many measurements were collected for each deal.
For example, let’s say an SP has one deal that’s retrievable and another that is not. Now consider two cases:
1. The task testing the retrievable deal produces 100 retrieval requests (accepted measurements) while the task testing the non-retrievable deal produces 50 retrieval requests (accepted measurements). …

fix: include minority results in RSR calculation

---

lib/retrieval-stats.js
test/retrieval-stats.test.js

I'd like to get visibility into the size of the majorities - is it a tight majority or a super majority?
Links:
- https://github.com/space-meridian/roadmap/issues/59

feat: record stats for majority vs. committee size ratio

---

bin/spark-evaluate.js
lib/cancel-stuck-txs.js

This should help prevent errors like
> spark-evaluate CANNOT SUBMIT SCORES FOR ROUND 14990n (CALL 9/9): Error: nonce has already been used 
As suggested in https://github.com/ethers-io/ethers.js/issues/4258#issuecomment-1705709167

Add use `NonceManager` to prevent non-serial nonce errors

---

index.js

I noticed that Spark Public Dashboard does not have data about measurements from yesterday.
https://stats.filspark.com/measurements/daily?from=2024-09-16&to=2024-09-19
```json
[
{
"day": "2024-09-16",
"accepted_measurement_count": 5749452,
"total_measurement_count": 13084627
},
{
"day": "2024-09-17",
"accepted_measurement_count": 6155666,
"total_measurement_count": 14074242
}
]
```
This data is produced as part of the periodic data aggregation in spark-evaluate:
```js
// Update top measurement stations every 12 hours
setInterval(() => refreshDatabase(createPgClient), 1000 * 60 * 60 * 12)
```
The current 12-hour interval does not work well enough - it’s almost 14 hours since we got complete data for yesterday, and yet our summary tables have not been updated yet.
IMO, it’s time to find a …

fix: refresh DB every 4 hours

---

lib/platform-stats.js
lib/public-stats.js
test/platform-stats.test.js

This is the only time-sensitive task remaining in [Fix the performance of the Station Public Dashboard](https://github.com/space-meridian/roadmap/issues/132). The change prevents our PG DB from consuming too much disk space.
I ran `rg daily_stations` in https://github.com/filecoin-station/spark-stats and we are no longer querying that table, so it's safe to stop writing new data.
I am keeping the table around, so that we can use the historical data stored in this table to backfill new tables we created as part of the fix.
Links:
- https://github.com/space-meridian/roadmap/issues/132

feat: stop populating daily_stations table

---

lib/cancel-stuck-transactions.js
package-lock.json
package.json

Otherwise while we're stuck waiting for replacement transactions to be confirmed, we're not trying to cancel any new stuck transactions.

fix cancel stuck transactions when previous run not yet finished

---

lib/typings.d.ts
test/evaluate.js
test/public-stats.test.js

Change the `string` type to an enum with the following variants:
| 'OK'
| 'HTTP_NOT_ADVERTISED'
| 'NO_VALID_ADVERTISEMENT'
| 'ERROR_FETCH'
| `ERROR_${number}`
| undefined
| null;

fix: tighten up indexer result enum

---

lib/preprocess.js
lib/retrieval-stats.js
lib/typings.d.ts
test/committee.test.js
test/helpers/test-data.js
test/preprocess.js
test/public-stats.test.js
test/retrieval-stats.test.js

Remove the following result codes:
- `ERROR_${number}`
- `BAD_GATEWAY`
- `GATEWAY_TIMEOUT`
Replace them with HTTP status codes prefixed with `HTTP_` if the
retrieval was performed directly over Trustless HTTP GW protocol
and `LASSIE_` if the retrieval was performed using Lassie. In the latter
case, the status code comes from Lassie, not the storage provider.

feat: distinguish HTTP status from Lassie status

---

lib/contracts.js

This makes us use eth_getFilterChanges which should now work. If it doesn't, this will let us give feedback.
See also https://github.com/filecoin-station/spark-api/pull/451

ie-contract: Disable JSON-RPC polling

---

bin/evaluate-measurements.js
bin/fetch-recent-miner-measurements.js

Usage:
```console
$ node bin/fetch-recent-miner-measurements.js f0...
...
$ node bin/evaluate-measurements measurements-f0....ndjson
→ evaluating round 19117n
→ added 183 accepted measurements from this round
→ evaluating round 19118n
→ added 0 accepted measurements from this round
→ evaluating round 19127n
→ added 181 accepted measurements from this round
→ evaluating round 19128n
→ added 0 accepted measurements from this round
Found 364 accepted measurements.
IPNI_ERROR_404                           364        (100%)
Wrote evaluation to evaluation-5bf6db8.txt
```
This is a first step towards evaluating arbitrary rounds. Next: https://github.com/filecoin-station/spark-evaluate/pull/402
__After merging, update Spark troubleshooting docs__

cli: split `fetch-recent-miner-measurements` and `evaluate-measurements`

---

lib/evaluate.js
lib/preprocess.js
lib/typings.d.ts
test/evaluate.js
test/preprocess.js

Move the validation step earlier to the preprocess/evaluate pipeline.  Measurements missing the indexer result are dropped as invalid.
This is the first step to refactor `fraudAssessment` field for more clarity, see https://github.com/filecoin-station/spark-evaluate/pull/396#discussion_r1850597708

feat: assert indexer_result during preprocessing

---

lib/evaluate.js
lib/public-stats.js
test/platform-stats.test.js
test/public-stats.test.js

Discovered while working on #442

refactor: remove unused param honestMeasurements

---

.depcheckrc
.github/workflows/ci.yml
package-lock.json
package.json

Partially Fixes: https://github.com/CheckerNetwork/roadmap/issues/221
I have integrated `depcheck` into the project to detect unused dependencies. Additionally, I have added a configuration file to exclude `@Types`, `TypeScript`, and `depcheck` from the analysis, as these may produce false positives.

Add depcheck for Unused Dependency Detection

---

lib/preprocess.js
test/preprocess.js

Fix the regression introduced by e2a458b (#475)
- Graphsync retrievals don't test HEAD request, see https://github.com/CheckerNetwork/spark-checker/commit/3f8edc5539ddf83f8cb2cc1ccdd534a7a1624f1f
- As a result, measurements for Graphsync retrievals have `head_status_code` set to undefined or null.
- The validation performed during the preprocessing step discarded such measurements as invalid.
This pull requests relaxes the validation during preprocessing to assert numeric `head_status_code` for HTTP retrievals only.

fix: accept Graphsync measurements without HEAD status

---

test/spark-api.js

Fixes a regression introduced in [#542](https://github.com/CheckerNetwork/spark-api/pull/542), where the allocators array was not considered in the expected test response.
This PR:
- Corrects the test expectations to account for the `allocators `array.
- Adds a new test case to validate responses that include a populated `allocators `array.
- Refactors the test into a table-driven format to reduce code duplication and improve maintainability.

fix: account for allocators array in test and refactor to table-driven format

---

lib/provider-retrieval-result-stats.js
lib/public-stats.js
test/public-stats.test.js

This PR has two commits to make the review easier:
- **refactor: fix test structure and names**
- **feat: exlude `IPNI_ERROR_5xx` measurements from RSR**
Links:
- https://github.com/CheckerNetwork/roadmap/issues/256
**feat: exlude `IPNI_ERROR_5xx` measurements from RSR**
Degradation of the IPNI service at cid.contact should not affect retrieval success rates.
This change is modifying the RSR calculations to exclude measurements with retrieval status `IPNI_ERROR_5xx` (e.g. `IPNI_ERROR_504`).
Important: we keep including `IPNI_ERROR_5xx` measurements in all other places. Most notably:
- Committees includes `IPNI_ERROR_5xx` measurements when looking for a majority consensus. This is important for the security of the protocol. If we excluded `IPNI_ERROR_5xx`s from the committee, then it would …

fix: exlude IPNI_ERROR_5xx measurements from RSR

---

lib/retrieval-stats.js
test/retrieval-stats.test.js

In the previous change (#512), I modified the code writing RSR to the database for spark-stats to exclude IPNI 5xx results from the calculation.
We need to apply the same change to RSR written to InfluxDB.
- We want the RSR in our internal dashboard to be consistent with the RSR in the public dashboard.
- I want to create an alert to let us know when the RSR unexpectedly drops. That alert must not be triggered by IPNI service degradations.
Note: I still want the result breakdowns to include IPNI 5xx errors.  I added a test to capture that requirement.
Links:
- https://github.com/CheckerNetwork/roadmap/issues/252

fix: exclude IPNI 5xx from "success rate" in Influx

---

lib/evaluate.js
test/retrieval-stats.test.js

Adds valid minority measurement results to the reported honest retrieval stats. 
Closes #446
Related to https://github.com/CheckerNetwork/spark-evaluate/pull/442#discussion_r1908899364

feat: include minority results in telemetry stats

---

lib/preprocess.js
test/preprocess.js

Some CIDs represent an empty file and Storacha returns HTTP 410 Gone error response in such case.
In this patch, I am fixing the function `fetchMeasurements` to skip the retrieval and return an empty list for such CIDs.
See also:
- https://github.com/CheckerNetwork/spark-api/pull/692

fix: skip downloading CIDs for empty files

---

.dockerignore

Helper scripts keep measurements cached in `.cache` directory. They should not be uploaded to Fly.io when building the Docker image to deploy. This is important when deploying spark-evaluate manually in emergencies.

chore: add .cache to Dockerignore
