CheckerNetwork/spark-evaluate

bin/spark-evaluate.js, fly.toml, package-lock.json, package.json
I created a new Sentry project `spark-evaluate`: https://protocol-labs-ip.sentry.io/projects/spark-evaluate/?project=4505906069766144
=> feat: setup Sentry integration for errors

lib/preprocess.js, test/preprocess.js
Link to:
- https://github.com/filecoin-station/spark/issues/18
=> feat: accept participant address in ETH 0x format

bin/spark-evaluate.js, index.js, lib/config.js, lib/evaluate.js, lib/spark-api.js, lib/typings.d.ts, test/evaluate.js
See https://github.com/filecoin-station/spark/issues/13
=> feat: reject measurements for unknown tasks

lib/telemetry.js
Example output:
```
Event: MeasurementsAdded { roundIndex: 274 }
PREPROCESS ROUND 274: Added measurements from CID bafybeidafjoe5enrirksegi6sork7gszhdxeawt5vqfbzbjbr3zhvkhmye
{ total: 18, valid: 18 }
TELEMETRY preprocess ve {
tags: {},
fields: {
round_index: '274i',
total_measurements: '18i',
valid_measurements: '18i',
fetch_duration_ms: '2068i'
},
name: 'preprocess'
}
```
=> feat: log telemetry to console

bin/spark-evaluate.js
I noticed all issues are linked to "development" environment in Sentry web UI.
Then I found a typo, which I am fixing in this pull request.
=> fix: sentry environment config in production

index.js
Stop spamming our Sentry monitoring.
Links:
- https://github.com/filecoin-station/spark-evaluate/issues/36
=> fix: wrap web3.storage ENOENT errors

.github/workflows/ci.yml
follow-up for https://github.com/filecoin-station/spark-api/pull/115
=> ci: verify Docker images can be built

lib/evaluate.js, lib/preprocess.js, lib/typings.d.ts, test/evaluate.js, test/preprocess.js
Links:
- https://github.com/filecoin-station/spark/issues/29
=> feat: reward one participant per inet group

lib/evaluate.js, test/evaluate.js
See https://github.com/filecoin-station/spark-evaluate/pull/53#discussion_r1379024015
=> fix: close empty & unknown rounds

.github/workflows/dependabot-auto-merge.yml
I copied the workflow file from https://github.com/filecoin-station/spark-api
=> ci: auto-merge Dependabot PRs

lib/preprocess.js, test/helpers/assertions.js, test/preprocess.js
Links:
- https://github.com/filecoin-station/spark-api/issues/144
=> telemetry: count spark_versions in measurements

lib/evaluate.js, lib/typings.d.ts, test/evaluate.js
=> Reward only first TN measurements per round. Closes #98

lib/retrieval-stats.js, test/retrieval-stats.test.js
=> Add `tasks_per_node` retrieval stats. Closes #78

bin/dry-run.js, bin/spark-evaluate.js, lib/config.js
=> Add auth to glif requests

bin/dry-run.js
A small improvement to make sub-sequent dry runs faster to complete.
=> dry-run: cache list of events queried from chain

bin/spark-evaluate.js, index.js, lib/on-contract-event.js, lib/preprocess.js, package-lock.json, package.json, test/evaluate.js
<del>Blocked by https://filecoinproject.slack.com/archives/CPFTWMY7N/p1705402931205099</del> Now with custom iteration function.
After deploying this, I'm planning to move the function to a separate repo, and add a test suite there. For now, I've run this successfully on my machine
=> Update to ethers v6

bin/dry-run.js
=> fix: ieContractWithSigner stub for dry-run

test/public-stats.test.js
=> test: add fine-grained tests for public-stats

lib/preprocess.js, lib/retrieval-stats.js, test/helpers/test-data.js, test/preprocess.js, test/retrieval-stats.test.js
Links:
- https://github.com/filecoin-station/spark/issues/40
- https://github.com/filecoin-station/spark-api/pull/204
=> feat: calculate stats for IPNI queries

lib/public-stats.js, lib/retrieval-stats.js, migrations/004.do.indexer-stats.sql, test/public-stats.test.js
This PR will be followed by another to expose this new data via HTTP (see https://github.com/filecoin-station/spark-stats).
Links:
- https://www.notion.so/pl-strflt/Moving-IPNI-queries-to-Spark-checkers-c58175c0f1c841e6bb82ac44a1472a98
- https://github.com/filecoin-station/spark/issues/40
- https://github.com/filecoin-station/roadmap/issues/84
=> feat: collect IPNI query results for public stats

lib/evaluate.js, lib/preprocess.js, lib/typings.d.ts, test/evaluate.js, test/preprocess.js
Links:
- https://github.com/filecoin-station/roadmap/issues/86
=> feat: reject measurements missing `indexerResult`

bin/dry-run.js
Update the dry-run script to accommodate the recent changes we made: upgrade to Ethers v6, refactor per-round data, and so on.
=> fix: dry-run

lib/preprocess.js, lib/typings.d.ts, test/preprocess.js
Fix the regression introduced by #158.
Links:
- https://github.com/filecoin-station/roadmap/issues/86
=> fix: indexer result field is in snake case

test/spark-api.js
Discovered in https://github.com/filecoin-station/spark-evaluate/actions/runs/8229849171/job/22501850835?pr=170
=> fix `spark-api` tests

.github/workflows/ci.yml
See the discussion in #205
I need to update this PR after we land #204
=> ci: set SENTRY_ENVIRONMENT to "CI"

test/spark-api.js
Discovered in https://github.com/filecoin-station/spark-evaluate/actions/runs/8995975403/job/24711757664?pr=214
=> fix `test/spark-api.js`

lib/platform-stats.js, migrations/007.do.add-daily-job-stats.sql, package-lock.json, package.json, test/platform-stats.test.js
Link: filecoin-station/roadmap#99
=> Feat: Added honest_measurement_count platform stat

bin/dry-run.js, bin/spark-evaluate.js, lib/ie-contract.js
Links:
- https://github.com/filecoin-station/roadmap/issues/107
=> refactor: extract `createMeridianContract` helper

lib/preprocess.js
As suggested [here](https://filecoinproject.slack.com/archives/C027XP5BTGB/p1717581326121119?thread_ts=1717165521.276339&cid=C027XP5BTGB)
=> preprocess: fix disable fetchMeasurements cache on retries

index.js
This allows us to create alerting for when no new events are being received.
=> telemetry: add `last_new_event_seen` with `age_ms`

lib/evaluate.js, lib/platform-stats.js, lib/public-stats.js, migrations/008.do.add-daily-all-job-stats.sql, test/platform-stats.test.js, test/public-stats.test.js
=> feat: track total jobs completed per station id

lib/evaluate.js, lib/preprocess.js, lib/typings.d.ts, package-lock.json, package.json, test/evaluate.js, test/helpers/assertions.js, test/helpers/test-data.js, test/integration.test.js, test/platform-stats.test.js, test/preprocess.js, test/public-stats.test.js, test/retrieval-stats.test.js, test/spark-api.js, tsconfig.json
=> chore: typecheck test files

lib/public-stats.js, migrations/009.do.daily-deals.sql, test/public-stats.test.js
See https://github.com/space-meridian/roadmap/issues/57
=> feat: daily deals stats: total/indexed/retrievable

index.js, lib/platform-stats.js, migrations/011.do.top-measurements-stations-mv.sql, migrations/012.do.top-measurements-stations-mv.sql, test/platform-stats.test.js
Link: https://github.com/space-meridian/roadmap/issues/118
=> feat: add materialized view for top stations by measurement count

lib/evaluate.js, lib/retrieval-stats.js
Links:
- https://github.com/space-meridian/roadmap/issues/59
=> refactor: import Measurement only once

test/spark-api.js
Fix the test failure introduced by this PR:
- https://github.com/filecoin-station/spark-api/pull/387
See also:
- https://github.com/filecoin-station/spark/issues/79
=> test: update expected round details

lib/evaluate.js, test/evaluate.js
https://my.papertrailapp.com/systems/9b22/events?focus=1759713909884985352&selected=1759713907217408007
=> fix don't retry scoring wrong round

bin/cancel-pending-tx.js
Example use (store `WALLET_SEED` in the `.env` file):
```
❯ node bin/cancel-pending-tx.js bafy2bzacecndrwpoggfk74wir5wlamqzkiw766dkxod7jnojsjzvyp2slj35y
```
Links:
- https://github.com/filecoin-station/spark-evaluate/issues/315
- https://filecoinproject.slack.com/archives/CRK2LKYHW/p1722432098249869
- https://filecoinproject.slack.com/archives/C0179RNEMU4/p1607269156412600?thread_ts=1606987775.021900&cid=C0179RNEMU4
=> feat: script to cancel a pending TX that got stuck

bin/spark-evaluate.js, lib/cancel-stuck-txs.js, package-lock.json, package.json, test/cancel-stuck-txs.test.js
Closes #315
On an interval, check the mempool for stuck transactions, and cancel them all.
In this first simple implementation, a transaction is considered "stuck" when it's older than the current IE round length of 20 minutes. This can later be improved by parsing the transaction payload and comparing the round index with the current IE round index.
Example output:
```
Checking for stuck transactions...
Transactions to cancel:
- bafy2bzaceborkhyvzoq3gfuqqy5z7q647yx2agyy6l6zshz3lhviaskf6cdew (age 20m)
- bafy2bzaceajr6r24yefuonrmbpo4rs756xrrud2knl6z7towqemomtxq7uv34 (age 20m)
- bafy2bzacecqq7o6mdvbddm7gxyfcsuo36lidcva32ajwicyfm4yjymrhhvwye (age 20m)
- bafy2bzaceaczqfxhcaqv4dhq2nqdfa5yhpn3gx27q337ntyrk76cghi4dd4ny (age 20m)
Calculating gas fees from the recent Send message …
```
=> Add auto cancel stuck transactions. Closes #315

lib/config.js
Unfortunately this endpoint has been unresponsive for quite some time now -> we're back to glif-only endpoints
=> Remove unresponsive chainup endpoint

lib/evaluate.js
=> Add retry failed `drand` requests. Closes #309

lib/platform-stats.js, migrations/014.do.top-measurement-participants-mv.sql, test/platform-stats.test.js
Relates to #311 and https://github.com/space-meridian/roadmap/issues/132
=> feat: rework top_measurement_participants_yesterday_mv  to use the new schema

lib/cancel-stuck-txs.js
https://github.com/ethers-io/ethers.js/blob/5aba4963e3e8ddfc912747076f5b7fe7a743cfe2/src.ts/transaction/transaction.ts#L1004
```js
assert(this.maxFeePerGas >= this.maxPriorityFeePerGas, "priorityFee cannot be more than maxFee", "BAD_DATA", { value: this });
```
=> Fix priority fee below max fee

lib/platform-stats.js, migrations/015.do.rename-platform-summary-table.sql, test/platform-stats.test.js
Related to #311 and based on discussion here: https://github.com/filecoin-station/spark-stats/pull/210#discussion_r1745279164
=> chore: rename daily_measurements_summary to daily_platform_stats

lib/cancel-stuck-transactions.js
Fixes https://space-meridian.sentry.io/issues/5903978203/?project=4505906069766144&referrer=github-pr-bot
=> cancel-stuck-transactions: fix return bigint type

lib/cancel-stuck-transactions.js, package-lock.json, package.json
Depends on https://github.com/filecoin-station/cancel-stuck-transactions/pull/2
=> cancel-stuck-transactions: fix don't report filfox errors to sentry

bin/spark-evaluate.js, lib/telemetry.js
After deploy: disable old token
=> telemetry: fix hide InfluxDB write token

bin/dry-run.js, bin/evaluate-measurements.js, bin/fetch-historic-measurements.js, bin/fetch-recent-miner-measurements.js
Based on https://github.com/filecoin-station/spark-evaluate/pull/401
=> bin: add `fetch-historic-measurements`

lib/evaluate.js
=> evaluate: fix retry `prepareProviderRetrievalResultStats()`

.github/workflows/dependabot-auto-approve-minor.yml
=> ci: add approve minor `dotenv` updates

lib/evaluate.js
=> Add breakdown of fraud detection timings. Closes #460

Dockerfile
Fixes[#243](https://github.com/CheckerNetwork/roadmap/issues/243)
=> Auto-update Node.js version in Dockerfile
